@startuml

:Socio:

:Biblioteca:

package biblioteca {
(Reservar Libro)
(Prestar Libro)
(Devolver Libro)
(Actualizar Catálogo)
}

Socio -- (Reservar Libro)
Socio -- (Devolver Libro)
Socio -- (Prestar Libro)
Biblioteca -- (Actualizar Catálogo)
Biblioteca -- (Prestar Libro)
@enduml