@startuml

:Empleado:
:Administrador:
package Empresa_Pedidos {
    (Introducir Pedido) -- Empleado
    (Cancelar Pedido) -- Empleado
    (Obtener Estado Pedido) -- Empleado
    (Borrar Pedido) -- Empleado
    (Buscar Pedido) -- Empleado
    (Alta Cliente) -- Empleado
    (Buscar Cliente) -- Empleado

    (Nuevo Producto) -- Administrador
    (Borrar Producto) -- Administrador

    (Alta Cliente) ..> (Introducir Pedido): <<extend>>
    (Introducir Pedido)..>(Buscar Cliente):<<include>>
    (Obtener Estado Pedido)..>(Buscar Pedido):<<include>>
    (Cancelar Pedido) ..> (Buscar Pedido) <<include>>
    (Introducir Pedido)<..(Pago en cuenta):<<extend>>
    (Introducir Pedido)<..(Pago con tarjeta):<<extend>>
}
@enduml